### ISSUE TITLE
initial setup with example code results in a segmentation fault / xen on linux

### ISSUE THREAD

**Issue by martinloos** [Wenzel/libmicrovmi#125] opened 2020-12-10 23:03 UTC
## Context

As discussed on twitter (@deiderajr) i receive a segmentation fault after using the mem-dump example code (same for other examples).

## Process

This is our testing environment:

[xlinfo.txt](https://github.com/Wenzel/libmicrovmi/files/5676035/xlinfo.txt)

Steps to reproduce the error:

1. Downloaded the repository from github (master branch)
2. cd to libmicrovmi/target/debug/examples
3. RUST_LOG=debug cargo run --features xen --example mem-dump <VM-Name>

Retrieving data with libvmi works (see terminal_libvmi.png).

![terminal_libvmi](https://user-images.githubusercontent.com/51302052/101840355-3a7cbb80-3b44-11eb-8fe4-72db09c40231.png)

## Expected result

Getting a correct .dump file

## Current result

Segmentation fault (see terminal_libmicrovmi.png)

![terminal_libmicrovmi](https://user-images.githubusercontent.com/51302052/101840336-32bd1700-3b44-11eb-8a3f-3dd9eb24b53d.png)

## End

If i missed important information please let me know. Thanks!

**Comment by Wenzel** [comment] 2020-12-11 00:08
Hi @martinloos , thanks for your detailed report.

I just tested libmirovmi's `mem-dump` example on a Xen VM, and it works on my side:
![Capture d’écran de 2020-12-11 01-01-14](https://user-images.githubusercontent.com/964610/101844379-8af81700-3b4c-11eb-95cd-f67ff85ce4aa.png)

I'm running Xen 4.11.4-pre, on ubuntu 20.04 (a Vagrant image)
libmicrovmi is on latest master, at `6a28dfe8ceb996cb2255ee014f0a68e0677f1223`

I am quite surprised to see a segfault
Can you try to run it with `rust-gdb` and bet a stacktrace ?
https://bitshifter.github.io/rr+rust/index.html#1

**Comment by martinloos** [comment] 2020-12-11 00:49
I tried running it with rust-gdb --args ./mem-dump <VM-Name> and the following was the output:

![terminal_rust-gdb_output](https://user-images.githubusercontent.com/51302052/101847179-ec22e900-3b52-11eb-8cc7-56e1434ac108.png)

**Comment by Wenzel** [comment] 2020-12-11 01:01
You need to run the `bt` command to get the stacktrace

**Comment by martinloos** [comment] 2020-12-11 01:12
![terminal_rust-gdb-bt_output](https://user-images.githubusercontent.com/51302052/101848622-38235d00-3b56-11eb-876c-14bed1c7f36d.png)

**Comment by Wenzel** [comment] 2020-12-11 01:23
Looks the error come from here:
https://github.com/Wenzel/xenstore/blob/master/src/lib.rs#L68

You could jump a few stack frames and check the value of `res`, see if it's a null pointer.
I would also print the value of the `c_path`, maybe the conversion from the Rust string to `CString` was incomplete, and the VM name we are looking for doesn't exist

This the path that we requested to read in the registry:
https://github.com/Wenzel/libmicrovmi/blob/master/src/driver/xen.rs#L27

**Comment by martinloos** [comment] 2020-12-11 01:50
Could you please elaborate on how I can do this? I saw the xenstore dependency in the Cargo.toml file. Should i modify this file to get the res + c_path values to check them?

**Comment by Wenzel** [comment] 2020-12-11 09:18
you don't need to modify xenstore, but print the local variables with the debugger, as you would do with `gdb`.
I haven't been using rust-gdb, but i suppose it's the same

use `up` and `down` to navigate the stack frames
use `p <var>` to print a variable

**Comment by rageagainsthepc** [comment] 2020-12-11 11:33
> Looks the error come from here:
https://github.com/Wenzel/xenstore/blob/master/src/lib.rs#L68

On a side note, I think we are leaking memory here. `xs_read` returns a malloced value and leaves it up to the caller to free it.
`CStr::from_ptr(res as *mut c_char).to_string_lossy().into_owned()` should convert the value to a rust string and return a copy. I am pretty sure the originial memory is just left dangling here.

**Comment by rageagainsthepc** [comment] 2020-12-11 11:50
The function that does the actual work here is `xs_talkv` https://github.com/xen-project/xen/blob/437211cb696515ee5bd5dae0ab72866c9f382a33/tools/xenstore/xs.c#L488
It will return `NULL` and set `errno` on error. So, we should definitely check for that.

**Comment by Wenzel** [comment] 2020-12-11 14:03
> On a side note, I think we are leaking memory here

Absolutely.
I only learned later how to free a C struct from Rust (here in kvmi crate):
https://github.com/Wenzel/kvmi/blob/master/src/lib.rs#L620

**Comment by martinloos** [comment] 2020-12-11 20:08
That's the output i get from the variables. I guess the marked part is wrong. Do you have any idea how to solve this error?

![terminal_printedvariables](https://user-images.githubusercontent.com/51302052/101949798-72433c00-3bf4-11eb-86c5-a727ea24bd2e.png)

**Comment by rageagainsthepc** [comment] 2020-12-12 09:26
@martinloos I have opened a [PR](https://github.com/Wenzel/xenstore/pull/5) that should get you closer to the root cause as it will no longer segfault but instead give you a well defined error message.

**Comment by martinloos** [comment] 2020-12-12 13:05
@rageagainsthepc Thank you for the work! I imported the branch as a dependency instead of the current one used like this:
`xenstore = { git = "https://github.com/rageagainsthepc/xenstore", branch = "error-handling-xs-read", optional = true }`

Then the `cargo build --features xen` command results in the following:

![terminal_build_error_prxenstore](https://user-images.githubusercontent.com/51302052/101984453-d5c77b00-3c81-11eb-82d9-59e8c5ae8bd8.png)

I found a stackoverflow discussion [https://stackoverflow.com/questions/33759072/why-doesnt-vect-implement-the-display-trait](url) which might point out the problem (in my opinion) which should originate here: [https://github.com/Wenzel/libmicrovmi/blob/6a28dfe8ceb996cb2255ee014f0a68e0677f1223/src/driver/xen.rs#L27](url)

**Comment by rageagainsthepc** [comment] 2020-12-12 13:20
@martinloos My PR has changed the API of the xenstore crate, so you can't just use it as a drop-in replacement in libmicrovmi. I'm waiting for @Wenzel to review the PR and publish a new version of the crate. If you want to test these changes, you should find calls to `xs.directory()` and `xs.read()` and call `unwrap()` on the result as a quick workaround.

**Comment by rageagainsthepc** [comment] 2020-12-12 22:28
@martinloos So you get a `Permission Denied` error while trying to read a domain name although you are root. Curious :thinking: 
@Wenzel do you have an idea?

**Comment by martinloos** [comment] 2020-12-12 23:01
@rageagainsthepc Yes that's correct. I can post our full setup if needed. I'm executing libmicrovmi from a MVM (Debian 4.19.16-1) which monitors a PVM (Ubuntu 16.04.9). Xen Version is 4.11.1-pre. Libvmi can retrieve data from the PVM.

**Comment by Wenzel** [comment] 2020-12-12 23:50
one thing: in your screenshot, you are already root, so you don't need sudo.

> @Wenzel do you have an idea?

Not at this point. Either the execution is done as simple user somehow, and we don't see it, or something else is at play here.

I did quick test, and tried to execute a program as normal user:
![Capture d’écran de 2020-12-13 00-43-32](https://user-images.githubusercontent.com/964610/101999344-4b603500-3cdc-11eb-9765-2091f548b29e.png)

It returns a permission denied error, but for `xen.rs:23`, which is:
https://github.com/Wenzel/libmicrovmi/blob/master/src/driver/xen.rs#L23

As your error is bit later, this confirms you are running as root.

We are following the same API calls that Libvmi is doing:
https://github.com/libvmi/libvmi/blob/master/libvmi/driver/xen/xen.c#L199

> I'm executing libmicrovmi from a MVM (Debian 4.19.16-1) which monitors a PVM (Ubuntu 16.04.9).

You mentionned that you try to introspect a paravirtualized guest.
I have only test libmicrovmi on fully virtualized guest (HVM)

Maybe we are missing a certain flag ?

:arrow_right: @martinloos can you try to setup the Windows XP image we are testing against ?
You can download it from here:
https://www.dropbox.com/s/0zycew5u3xnf8m7/winxp.qcow2?dl=0

I am using libvirt and `virt-manager` to manage my Xen domains, so it creates the Xen config file automatically.

**Comment by martinloos** [comment] 2020-12-13 00:17
@Wenzel Sure i can try that. As i work on a provided environment of my university i need to aks my professor for permissions to do so. I'll get back to you here as soon as I have any news.

**Comment by dl9rdz** [comment] 2020-12-14 11:31
There is a simple explanation for the issue: We are running introspection code in a dedicated monitoring virtual machine, not in Dom0 (see https://ieeexplore.ieee.org/document/7847045 for details). This domain has access to xenstore only to /local/domain and to /local/domain/<id>/name only for id's with the same owner as the monitoring virtual machine, it results in an access denied from xenstore for all other ids.

This works fine with plain libvmi. It would be nice for libmicrovmi to just ignore all ids for which the name is not accessible. Maybe @martinloos can prepare a pull request for such a change. (libvmi skips those entries in https://github.com/libvmi/libvmi/blob/master/libvmi/driver/xen/xen.c#L213)

**Comment by Wenzel** [comment] 2020-12-15 21:21
Closing this issue since https://github.com/Wenzel/libmicrovmi/pull/128#issuecomment-745522470 confirms that the provided fix works.

**Closed by Wenzel** 2020-12-15 21:21 UTC
