### ISSUE TITLE
mem-dump.rs writes invalid memory dumps

### ISSUE THREAD

**Issue by dl9rdz** [Wenzel/libmicrovmi#132] opened 2020-12-15 21:33 UTC
> > Volatility was unable to read a requested page: Page error 0xffff81e13858 in layer primary (Page Fault at entry 0x0 in table page directory)

> Strange, are you using Volatility3 ?
> Maybe open an issue on their repo, they will get back to you.

The problem is that mem-dump.rs does not create a valid memory dump, in the sense that it simply skips non-accessible pages, and thus physical address and offset in dump file will not match. Volatility depends on both being the same.

Something like this results in a working dump file (as sparse file, so not wasting disk space). Tested on Linux only, I am not familiar with Windows, if it supports sparse file that way as well.
```
--- a/examples/mem-dump.rs
+++ b/examples/mem-dump.rs
@@ -1,6 +1,9 @@
 use std::fs::File;
 use std::io::Write;
 use std::path::Path;
+use std::io::SeekFrom;
+use std::io::Seek;
+use std::convert::TryInto;
 
 use clap::{App, Arg, ArgMatches};
 use env_logger;
@@ -56,7 +59,9 @@ fn main() {
                     .write_all(&buffer)
                     .expect("failed to write to file");
             }
-            Err(_error) => (),
+            Err(_error) => {
+               dump_file.seek(SeekFrom::Current(PAGE_SIZE.try_into().unwrap())).expect("failed to seek in file");
+           },
         }
     }


```

**Comment by Wenzel** [comment] 2020-12-15 21:52
> The problem is that mem-dump.rs does not create a valid memory dump, in the sense that it simply skips non-accessible pages, and thus physical address and offset in dump file will not match. Volatility depends on both being the same.

Thanks for the hint.
I wanted to test your fix on my Windows XP VM, but in both cases, Volatility3 fails to run the plugins because of symbols requirements being unsatisfied.

I will check with the Volatility guys on this.

**Comment by martinloos** [comment] 2020-12-15 22:55
@dl9rdz I can confirm that this fixed it for Linux OS.

**Comment by Wenzel** [comment] 2021-03-02 18:04
Fixed by https://github.com/Wenzel/libmicrovmi/pull/171

Please reopen this issue if necessary.

thank you for reporting it !

**Closed by Wenzel** 2021-03-02 18:04 UTC
Labels: bug
